toDoProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rest_framework import routers

from toDo import views, listClassViews, itemClassViews, restViews

# router = routers.DefaultRouter()
# router.register(r'users', restViews.)
# router.register(r'groups', restViews.GroupViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('django.contrib.auth.urls')),
    url(r'^$',views.home),
    url(r'^todolist/$',listClassViews.todo_ListView.as_view(),name="todo-lists"),
    url(r'todolist/create$', listClassViews.todo_CreateView.as_view()),
    url(r'todolist/(?P<pk>[0-9]+)/delete$', listClassViews.todo_DeletelView.as_view()),
    url(r'todolist/(?P<pk>[0-9]+)$',listClassViews.todo_DetailView.as_view(),name="todo-item"),
     url(r'todolist/(?P<pk>[0-9]+)/update$',listClassViews.todo_UpdateView.as_view()),
    url(r'todolist/(?P<id>[0-9]+)/create$',itemClassViews.item_CreateView.as_view()),
    url(r'todoitem/(?P<id>[0-9]+)$',itemClassViews.item_ListView.as_view(),name="todo-items"),
    url(r'todolist/(?P<id>[0-9]+)/(?P<pk>[0-9]+)/update', itemClassViews.item_UpdateView.as_view()),
    url(r'todolist/(?P<id>[0-9]+)/(?P<pk>[0-9]+)/delete', itemClassViews.item_DeleteView.as_view()),
    url(r'^api/todolists/$', restViews.todolist),
    url(r'^api/todolists/(?P<pk>[0-9]+)/$', restViews.todolist_detail),
    url(r'^api/todolists/(?P<id>[0-9]+)/todoitems/$', restViews.Item_list),
    url(r'^api/todolists/[0-9]+/todoitems/(?P<pk>[0-9]+)$', restViews.Item_detail),

]

toDo/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class ToDoList(models.Model):
    name=models.CharField(max_length=50)
    created=models.DateField()
    user = models.ForeignKey(User)
    def ___str___(self):
        return self.name

class ToDoItem(models.Model):
    description=models.CharField(max_length=256)
    duedate=models.DateField()
    completed=models.BooleanField(default=False)
    name=models.ForeignKey(ToDoList)
    user = models.ForeignKey(User)

toDo/forms.py
from django.forms import ModelForm
from toDo.models import ToDoList

class ContactAjaxForm(ModelForm):
    class Meta:
        model=ToDoList

toDo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from models import *
from django.template import loader
from django.forms import inlineformset_factory
# def create(request):
#     BookFormSet = inlineformset_factory(ToDoList, ToDoItem, fields=('description','duedate','completed',))
#     author = ToDoList.objects.get(name='Mike Royko')
#     formset = BookFormSet(instance=author)

def test(request):
    lis=ToDoList.objects.all()
    lo=loader.get_template('todlist.html')
    r=lo.render(context={'t_list':lis})
    return HttpResponse(r)

def items(request,id):
    lis = ToDoItem.objects.filter(name_id=id)
    lo = loader.get_template('todoitems.html')
    r = lo.render(context={'t_items': lis})
    return HttpResponse(r)

def home(request):
    return render(request, 'home.html')

templates/home.html
<!DOCTYPE html>
<html>
<head>
  <title>TO-DO bRO!</title>
<!--  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->
    {% load  staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <style>
  body {
      position: relative;
  }
  #section1 {padding-top:50px;height:550px;color: #fff; background-color: mediumpurple;}
  #section2 {padding-top:50px;height:550px;color: #fff; background-color: #00b2b4;}
  #section3 {padding-top:50px;height:550px;color: #fff; background-color: yellowgreen;}
  </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
<nav class="navbar navbar-inverse navbar-fixed-top navbar-success">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="color: red;font-size: 22px">TO-DO bRO!</a>
    </div>
    <div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li style="margin-left: 1100px;margin-top: 3px;"><button type="button" class="btn btn-warning btn-lg"><a href="login">login</a></button></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div id="section1"class="container-fluid">
  <h1 style="text-align: center; font-size: 50px;">Your work, your way</h1>
  <h2 style="text-align:center;">Customize your to do list on any Windows platform with the task manager that has been designed specifically for Microsoft’s modern products and features.</h2>
</div>
<div id="section2" class="container-fluid">
    <center>
  <h1>At your FingerPrints</h1>
  <h2>Plan your day and stay productive on-the-go with Todoist on your Windows Phone, desktop, and 2-in-1 laptop/tablet hybrid. Plus, you can access Todoist on 10+ other platforms.
</h2>
        </center>
</div>
<div id="section3" class="container-fluid">
    <center>
  <h1>Collaborate on shared tasks</h1>
  <h2>Assign and share tasks, discuss projects in real-time, and see beautifully displayed media with Todoist for Windows 10’s exclusive 3-pane view.
</h2>
    </center>
</div>
</body>
</html>

templates/toDo/todoitem_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>item delete</title>
</head>
<body>
<form method="post">
     {% csrf_token %}
    <p>are you sure you want to delete?</p>
    <input type="submit" value="submit"/>
</form>
</body>
</html>

templates/toDo/todoitem_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create todo item</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <table>{{ form.as_p }}</table>
    <input type="submit" value="create">
</form>
</body>
</html>

templates/toDo/todoitem_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>items</title>
</head>
<body>
{% for x in todoitem_list %}
    <h1>{{ x.description}}</h1>
{% endfor %}
</body>
</html>

templates/toDo/todolist_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>delete</title>
</head>
<body>
<form method="post">
     {% csrf_token %}
    <p>are you sure you want to delete?</p>
    <input type="submit" value="submit"/>
</form>
</body>
</html>

templates/toDo/todolist_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>items</title>
</head>
{% load  staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
          <button  type="button" class="btn btn-success" style="font-size: 40px;margin-left: 400px;"><a href="{{ todolist.id }}/create">add item</a></button>
        </div>
        </div>
</div>
<center>
    <table class="table table-hover bg-success" style="width: 100% ;height: 100px;">
        <th style="text-align:center;font-size:60px;background-color: blueviolet;color: gold;font-family: 'Agency FB';">description</th>
        <th style="text-align:center;font-size:60px;background-color: blueviolet;color: gold;font-family: 'Agency FB';">duedate</th>
        <th style="text-align:center;font-size:60px;background-color: blueviolet;color: gold;font-family: 'Agency FB';">completed?</th>
        {% for item in todolist.todoitem_set.all %}
            <tr>
            <td style="text-align: center;padding:15px;font-size: 25px;">{{ item.description }}</td>
            <td style="text-align: center;padding:15px;font-size: 25px;">{{ item.duedate }}</td>
            <td style="text-align: center;padding:15px;font-size: 25px;">{{ item.completed }}</td>
            <td style="width:7%;"><button type="button" class="btn btn-warning"><a href="{{ item.name_id }}/{{ item.id }}/update">update</a></button></td>
            <td style="width:5%;"><button  type="button" class="btn btn-danger"><a href="{{ item.name_id }}/{{ item.id }}/delete">delete</a></button></td>
            </tr>
        {% endfor %}
    </table>
    </center>
</body>
</html>

templates/toDo/todolist_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create todo_list</title>
</head>
<body>
<h1>create to do lists</h1>
<h2>{{ jails }}</h2>
<form action="" method="post">
    {% csrf_token %}
<table>{{ form.as_p}}</table>
    <input type="submit" value="create"/>
</form>
</body>
</html>

templates/todlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo_lists</title>
    <style>
        th, td {
    padding: 20px;
}
    </style>
</head>
{% load  staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
<body background="images/backGround.jpg">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
          <button  type="button" class="btn btn-success" style="font-size: 40px;margin-left: 400px;"><a href="create">add list</a></button>
        </div>
        </div>
</div>
<div class="container">
    <center>
    <table class="table table-hover bg-success" style="width: 100% ;height: 100px;">
        <th style="text-align:center;font-size:60px;background-color: blueviolet;color: gold;font-family: 'Agency FB';" >TO-DO LISTS</th>
    <th style="background-color: blueviolet;"></th>
        {% for li in todolist %}
            <tr>
            <td style="text-align: center;padding:15px;font-size: 25px;"><a href="{{ li.id }}">{{li.name}}</a></td>
            <td style="background-color:lightcyan;color:black;width:15%;font-size: 15px;">created on:{{li.created}}</td>
            <td style="width:7%;"><button type="button" class="btn btn-warning"><a href="{{ li.id }}/update">update</a></button></td>
            <td style="width:5%;"><button  type="button" class="btn btn-danger"><a href="{{ li.id }}/delete">delete</a></button></td>
            </tr>
        {% endfor %}
    </table>
    </center>
</div>
</body>
</html>

templates/todoitems.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List Items</title>
    <style>
        td{
            padding: 40px;
        }
    </style>
</head>
<body style="background-color: #9d9d9d">
<h1 style="text-align: center;color:gold;background-color:blue;">Items are:</h1>
<table style="font-size: 40px;color:yellow;padding: 30px;border: dashed;text-align: center;margin-left: 260px;">
<center>
<th>description</th>
<th>due date</th>
<th>checked</th>
{% for i in t_items %}
    <tr>
        <td>{{ i.description }}</td>
        <td>{{ i.duedate }}</td>
        <td>{{ i.completed }}</td>
    </tr>
    </center>
{% endfor %}
</table>
</body>
</html>